alter table CLASS1_BUSINESS add constraint FK_CLASS1_BUSINESS_CONTACT_PERSON foreign key (CONTACT_PERSON_ID) references CLASS1_CITIZEN(ID);
create unique index IDX_CLASS1_BUSINESS_UNIQ_BUSINESS_REGISTRATION_NUMBER on CLASS1_BUSINESS (BUSINESS_REGISTRATION_NUMBER) ;
create index IDX_CLASS1_BUSINESS_CONTACT_PERSON on CLASS1_BUSINESS (CONTACT_PERSON_ID);
